[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
delegator = "DTLVZKAFzv9JFYh6vXyBQdCoFcFspqMh6yCmmz1FyKCD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"